### ISSUE TITLE
drop extension pg_strom: ERROR:  cannot drop type int1 because it is required by the database system

### ISSUE THREAD

**Issue by MattiL** [heterodb/pg-strom#584] opened 2023-03-14 13:25 UTC
Extension pg_strom cannot be dropped in a PostgreSQL 15.2 database that had the extension created. I got the following error message. The operating system was Red Hat Enterprise Linux 9.1.

db=# drop extension pg_strom;
ERROR:  cannot drop type int1 because it is required by the database system

**Comment by MattiL** [comment] 2023-03-14 14:09
[root@rhel9 ~]# systemctl status -l postgresql-15
● postgresql-15.service - PostgreSQL 15 database server
     Loaded: loaded (/usr/lib/systemd/system/postgresql-15.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/postgresql-15.service.d
             └─pg_strom.conf
     Active: active (running) since Tue 2023-03-14 15:13:39 EET; 32min ago
       Docs: https://www.postgresql.org/docs/15/static/
    Process: 1921256 ExecStartPre=/usr/pgsql-15/bin/postgresql-15-check-db-dir ${PGDATA} (code=exited, status=0/SUCCESS)
   Main PID: 1921261 (postmaster)
      Tasks: 9 (limit: 48114)
     Memory: 798.5M
        CPU: 1.308s
     CGroup: /system.slice/postgresql-15.service
             ├─1921261 /usr/pgsql-15/bin/postmaster -D /var/lib/pgsql/15/data/
             ├─1921265 "postgres: logger "
             ├─1924117 "postgres: checkpointer "
             ├─1924118 "postgres: background writer "
             ├─1924141 "postgres: walwriter "
             ├─1924142 "postgres: autovacuum launcher "
             ├─1924143 "postgres: PG-Strom Program Builder-1 "
             ├─1924144 "postgres: PG-Strom Program Builder-0 "
             └─1924145 "postgres: logical replication launcher "

maalis 14 15:13:38 rhel9 systemd[1]: Stopped PostgreSQL 15 database server.
maalis 14 15:13:38 rhel9 systemd[1]: postgresql-15.service: Consumed 21.279s CPU time.
maalis 14 15:13:38 rhel9 systemd[1]: Starting PostgreSQL 15 database server...
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.656 EET [1921261] LOG:  NVRTC 12.1 is successfully loaded.
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.661 EET [1921261] LOG:  HeteroDB Extra module loaded [api_version=20221225,cufile=off,nvme_strom=off]
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.661 EET [1921261] LOG:  PG-Strom version 3.4 built for PostgreSQL 15 (git: HEAD)
maalis 14 15:13:38 rhel9 postmaster[1921263]: gpuinfo:455  failed on nvmlInit: Driver Not Loaded
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.761 EET [1921261] LOG:  redirecting log output to logging collector process
maalis 14 15:13:38 rhel9 postmaster[1921261]: 2023-03-14 15:13:38.761 EET [1921261] HINT:  Future log output will appear in directory "log".
maalis 14 15:13:39 rhel9 systemd[1]: Started PostgreSQL 15 database server.

**Comment by kaigai** [comment] 2023-03-15 00:45
It is likely because we enforce oid of `int1` type `606` by system catalog modification.
This is fixed on the upcoming v5.x series but still under active development.

**Comment by kaigai** [comment] 2023-05-13 01:24
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.

**Closed by kaigai** 2023-05-13 01:24 UTC
