### ISSUE TITLE
Can not return results if the option  "--device-debug" is blocked.

### ISSUE THREAD

**Issue by arron-lyu** [heterodb/pg-strom#225] opened 2016-02-16 03:05 UTC
Hello,
I encounter a problem when I study pg_strom.
I  built the PostgreSQL 9.5 without  --enable-debug, and I created the tables using the script _testdb.sql_. If I block the code from line 663 to line 666 in _cuda_program.c_ like this:
`//#ifdef PGSTROM_DEBUG`
`// options[opt_index++] = "--device-debug";`
`// options[opt_index++] = "--generate-line-info";`
`//#endif`

This SQL: _SELECT cat, count(*), avg(ax) FROM t0 NATURAL JOIN t1 GROUP BY cat_ cannot return results, it seems that pgstrom is locked and is in an endless loop. If I don't block the code `options[opt_index++] = "--device-debug"`, pgstrom can work.

what's the problem? Thanks.

The all settings are default settings, my GPU is K80, CUDA is 7.0, and 
shared_buffers = 30GB
work_mem = 30GB

**Comment by kaigai** [comment] 2016-02-16 03:17
I have two questions.

Do you use the latest master branch?
I've fixed similar problem a few weeks before.

Can you reproduce the problem with pg_strom.cuda_visible_devices=0 or 1 (it needs restart).
K80 looks 2x K40 GPUs from the software point of view. I don't have enough amount of debug on multi GPUs environment yet, so I like to check whether you can reproduce the problem on single GPU environment.

Thanks,

**Comment by arron-lyu** [comment] 2016-02-16 07:50
PGstrom is the latest master branch, I downloaded yesterday.
I set pg_strom.cuda_visible_devices=0 and restart, but didn't work, so I changed the code, the final settings are: 

```
SELECT name,setting FROM pg_settings WHERE name LIKE 'pg_strom%';
              name               |  setting   
---------------------------------+------------
 pg_strom.bulkexec               | on
 pg_strom.chunk_size             | 15872
 pg_strom.chunk_size_limit_ratio | 6
 pg_strom.chunk_size_margin      | 1.25
 pg_strom.cuda_visible_devices   | 0
 pg_strom.debug_cuda_coredump    | off
 pg_strom.debug_force_gpupreagg  | off
 pg_strom.debug_force_gpusort    | off
 pg_strom.debug_kernel_source    | off
 pg_strom.enable_gpuhashjoin     | on
 pg_strom.enable_gpunestloop     | on
 pg_strom.enable_gpupreagg       | on
 pg_strom.enable_gpuscan         | on
 pg_strom.enable_gpusort         | off
 pg_strom.enabled                | on
 pg_strom.gpu_dma_cost           | 1
 pg_strom.gpu_operator_cost      | 7.8125e-05
 pg_strom.gpu_setup_cost         | 4000
 pg_strom.gpu_tuple_cost         | 0.0003125
 pg_strom.max_async_tasks        | 32
 pg_strom.max_workers            | 4
 pg_strom.num_threads_margin     | 1.1
 pg_strom.perfmon                | off
 pg_strom.program_cache_size     | 49152
 pg_strom.pullup_outer_scan      | on
(25 rows)
```

I waited 10 minutes, no results are returned, and  fell in endless loop.
I used nvidia-smi to get GPU info when pgstrom is running, the info is:
```
+------------------------------------------------------+                       
| NVIDIA-SMI 346.59     Driver Version: 346.59         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:85:00.0     Off |                  Off |
| N/A   30C    P8    28W / 149W |     56MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:86:00.0     Off |                  Off |
| N/A   51C    P0    96W / 149W |   1553MiB / 12287MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    1      7022    C   postgres: postgres postgres [local] SELECT    1486MiB |
|    1      7184    C   ...bgworker: nvcc launcher - crc ff8497cc        4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by arron-lyu** [comment] 2016-02-17 09:09
I downloaded latest version **d8b01fd** and tested. Whether `options[opt_index++] = "--device-debug";` is blocked or not, pg_strom  fell in endless loop. But in last version, if  `options[opt_index++] = "--device-debug";` is not blocked, pg_strom can return results. I have set pg_strom.cuda_visible_devices to 0.
I will test with K40, but I don't think it's problem of multi-GPU.

**Comment by kaigai** [comment] 2016-02-18 00:18
I've still not succeeded to reproduce the problem.
Nowadays PGSTROM_DEBUG is not enabled unless you specify the label in Makefuke.custom, so '--device-debug' shall not be activated usually.

I often see the later infinite loop at the cuda_control.c during the development, when device code does not respond.

I hope you trying the latest 'dynpara' branch, instead of the 'master'.
It contains fundamental reworks around GpuJoin, and will be merged to the master branch.
It is not productive to have deep investigation on the current master.
(at least, I could not reproduce the problem in this revision...)

Thanks,

**Comment by kaigai** [comment] 2016-02-18 00:44
In the latest code also, I could find GpuHashJoin tried to walk on the hash table infinitely in another workloads.
It is a unresolved problem, and I'm now under investigation for this.

**Comment by kaigai** [comment] 2016-02-18 02:19
c93249bb50d3bcd1d020e99bdb868a0f23b44474 fixed up one potential (nearly) infinite loop problem when inner table contains all-null join keys.
However, your dataset is constructed with testdb.sql script, so problems around NULL value will hit....

**Comment by arron-lyu** [comment] 2016-02-18 04:58
I tested d8b01fd with K40, pg_strom can return results. So, the K80 does not suit for pg_strom.

**Closed** 2018-04-29 02:28 UTC
